export const ADD_INGREDIENT_IN_CONSTRUCTOR = 'ADD_INGREDIENT_IN_CONSTRUCTOR';
export const REMOVE_INGREDIENT_IN_CONCTRUCTOR = 'REMOVE_INGREDIENT_IN_CONCTRUCTOR';
export const BUN_SELECTOR = 'BUN_SELECTOR';