export const GET_DATA_REQUEST = 'GET_DATA_REQUEST';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const GET_DATA_ERROR = 'GET_DATA_ERROR';
export const INGREDIENT_AMOUNT_INCREASE = 'INGREDIENT_AMOUNT_INCREASE';
export const INGREDIENT_AMOUNT_DECREASE = 'INGREDIENT_AMOUNT_DECREASE';